- name: installing Python pip
  apt:
    name: python-pip
    state: latest

- name: installing Python virtualenv
  apt:
    name: python-virtualenv
    state: latest

- name: removing venv
  file:
    path: /etc/hermes/venv
    state: absent

- name: installing venv
  command: virtualenv -p python3 /etc/hermes/venv

- name: updating venv pip
  pip:
    name: pip
    state: latest
    virtualenv: /etc/hermes/venv
    extra_args: -vvv
