- name: generating nvidia xconfig
  command: nvidia-xconfig --enable-all-gpus --allow-empty-initial-configuration --cool-bits=28

- name: copying xserver binary
  copy:
    src: xserver
    dest: /usr/bin/
    mode: 0755

- name: copying xserver service file
  copy:
    src: xserver.service
    dest: /etc/systemd/system/
    mode: 0444

- name: enabling xserver service in systemd
  systemd:
    name: xserver.service
    enabled: yes
    state: restarted
    daemon_reload: yes
